### ISSUE TITLE
sonar doesn't start because of conection refused to database

### ISSUE THREAD

**Issue by mercuriete** [marcelbirkner/docker-ci-tool-stack#16]
steps for reproduce:
1 - install docker tools in windows
2 - do a compose up -d
3 - everything runs ok but sonar.

some output:

2016.04.06 10:57:01 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
at org.sonar.core.persistence.DefaultDatabase.checkConnection(DefaultDatabase.java:117) ~[sonar-core-5.1.2.jar:na]
at org.sonar.core.persistence.DefaultDatabase.start(DefaultDatabase.java:73) ~[sonar-core-5.1.2.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45-internal]
at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:91) ~[sonar-plugin-api-5.1.2.jar:na]
at org.sonar.server.platform.Platform.startLevel1Container(Platform.java:96) ~[sonar-server-5.1.2.jar:na]
at org.sonar.server.platform.Platform.init(Platform.java:72) ~[sonar-server-5.1.2.jar:na]
at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-5.1.2.jar:na]
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4720) [tomcat-embed-core-8.0.18.jar:8.0.18]
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154) [tomcat-embed-core-8.0.18.jar:8.0.18]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.18.jar:8.0.18]
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.0.18.jar:8.0.18]
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399) [tomcat-embed-core-8.0.18.jar:8.0.18]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45-internal]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45-internal]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45-internal]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45-internal]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
at org.sonar.core.persistence.DefaultDatabase.checkConnection(DefaultDatabase.java:115) ~[sonar-core-5.1.2.jar:na]
... 27 common frames omitted
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by mercuriete** [comment]
apart from that, thank you for your work.
i am learning a lot about docker and docker-compose and continous integration.
thank you very much.

**Comment by rocc0** [comment]
line 36 in docker-compose.yml
`- SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar` replace localhost with IP of your docker-machine. You can discover IP by running `docker-machine ip` command

**Comment by marcelbirkner** [comment]
Hi @mercuriete 

can you try it again. I replaced the deprecated Links feature with "docker network". 
I also added a missing depends_on relation.

Greetings,
Marcel

**Comment by mercuriete** [comment]
Hi again.
Sonar does work now. But now gitlab and node-chrome-debug and node-firefox-debug are not working.

steps to reproduce:
1) git clone
2) docker-compose up -d
3) see log output.

i will put some output:
node-chrome-debug:
/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 34: get_server_num: command not found
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...



node-firefox-debug:
/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 34: get_server_num: command not found
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...


gitlab:

Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis...........................................................

**Comment by mercuriete** [comment]
node-chrome-debug and firefox dies almost instantainly.

gitlab waits a long period and it seems that it can't connect with redis. but i'm not sure.

Thank you very much.

**Comment by marcelbirkner** [comment]
Hi @mercuriete 

I am running the toolchain on MacOS (16GB RAM) with the latest version of the Docker Toolbox (Docker 1.10).
Which version are you using?

Greetings,
Marcel

**Comment by pcornelissen** [comment]
FYI: The latest version of the toolbox is 1.11 ;-)

**Comment by mercuriete** [comment]
i had 1.10.3. I'm installing 1.11.1.
Thanks for pointing that issue.
:)

**Comment by CycleDave** [comment]
@marcelbirkner please can you give a bit more detail about what you did to fix it? For example: Are those changes you made, to configuration files? Where are they located, what settings did you change, where did you add the links you describe, what were the links?
We are seeing the same problem and can't see a way forward.

**Comment by CycleDave** [comment]
Issue solved by dropping the Docker version back down to Docker version 1.12.5, build 7392c3b

**Comment by CycleDave** [comment]
We found this was cured by:

1. Stopping and starting the Docker daemon, after this start SonarQube and it connects to the database.
2. Further crashes were caused by Puppet client configuration. Turning off the Puppet client stopped crashes. This is most likely misconfiguration and not a fundamental incompatibility with SQ.
