### ISSUE TITLE
Tried proxying jenkins.telemetry.Correlator to support a circular dependency, but it is not an interface.

### ISSUE THREAD

**Issue by 87abhii** [marcelbirkner/docker-ci-tool-stack#70]
Loading /var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/models/use_cases/create_project_for_branch.rb
Jan 28, 2019 12:10:56 AM hudson.plugins.ansicolor.PluginImpl start
INFO: AnsiColor: eliminating boring output (https://github.com/jenkinsci/ansicolor-plugin)
Jan 28, 2019 12:11:10 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Jan 28, 2019 12:11:10 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=jenkins.telemetry.Correlator, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Tried proxying jenkins.telemetry.Correlator to support a circular dependency, but it is not an interface.

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:432)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:394)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:385)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:493)
	at hudson.ExtensionList.load(ExtensionList.java:380)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:192)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at hudson.model.User.load(User.java:212)
	at hudson.model.User.<init>(User.java:166)
	at hudson.model.User.getOrCreate(User.java:537)
	at hudson.model.User.getOrCreate(User.java:484)
	at hudson.model.User.getById(User.java:673)
	at hudson.model.User.get(User.java:656)
	at hudson.model.User.current(User.java:640)
	at hudson.plugins.jobConfigHistory.PluginUtils.isUserExcluded(PluginUtils.java:121)
	at hudson.plugins.jobConfigHistory.JobConfigHistorySaveableListener.onChange(JobConfigHistorySaveableListener.java:55)
	at hudson.model.listeners.SaveableListener.fireOnChange(SaveableListener.java:81)
	at hudson.model.Descriptor.save(Descriptor.java:874)
	at jenkins.telemetry.Correlator.<init>(Correlator.java:51)
	at jenkins.telemetry.Correlator$$FastClassByGuice$$5678e8d6.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:432)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:394)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:385)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:493)
	at hudson.ExtensionList.load(ExtensionList.java:380)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1525)
	at hudson.plugins.sonar.SonarGlobalConfiguration.migrate(SonarGlobalConfiguration.java:96)
	at hudson.plugins.sonar.SonarPlugin.postInitialize(SonarPlugin.java:48)
	at hudson.PluginManager$2$1$2.run(PluginManager.java:543)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 28, 2019 12:11:11 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
INFO: Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
Jan 28, 2019 12:11:11 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.configfiles.GlobalConfigFiles$1 in file:/var/jenkins_home/plugins/config-file-provider/WEB-INF/lib/config-file-provider.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
Jan 28, 2019 12:11:12 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
INFO: Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
Jan 28, 2019 12:11:13 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Jan 28, 2019 12:11:13 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Jan 28, 2019 12:11:14 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Jan 28, 2019 12:11:15 AM jenkins.util.groovy.GroovyHookScript execute
INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
Jan 28, 2019 12:11:15 AM hudson.model.AllView migrateLegacyPrimaryAllViewLocalizedName
INFO: JENKINS-38606 detected for AllView in hudson.model.Hudson@7ca55b70; renaming view from All to all
Jan 28, 2019 12:11:15 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Jan 28, 2019 12:11:17 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Jan 28, 2019 12:11:18 AM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Jan 28, 2019 12:11:24 AM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource default
Jan 28, 2019 12:11:25 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
Jan 28, 2019 12:11:25 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Ant.AntInstaller
Jan 28, 2019 12:11:25 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.plugins.sonar.MsBuildSonarQubeRunnerInstaller
Jan 28, 2019 12:11:25 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.plugins.sonar.SonarRunnerInstaller
Jan 28, 2019 12:11:26 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.plugins.gradle.GradleInstaller
Jan 28, 2019 12:11:27 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tools.JDKInstaller
Jan 28, 2019 12:11:27 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 12,206 ms
--> setting agent port for jnlp
--> setting agent port for jnlp... done
PXT7972TA13MAC:opt user$ 

Please if someone can help

thanks

**Comment by dennyzhang** [comment]
See the exact same error message.

**Comment by yorammi** [comment]
according to this page: https://jenkins.io/doc/upgrade-guide/2.138/ a restart of the server make this error disapear

**Comment by markshep** [comment]
Did you find out how to fix this?  I'm getting it with the latest Jenkins LTS (2.440.3):
```
2024-04-17 23:03:38.169+0000 [id=34]    WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=jenkins.telemetry.Correlator, annotation=[none]]; skipping this component
 com.google.inject.ProvisionException: Unable to provision, see the following errors:

 1) [Guice/CanNotProxyClass]: Tried proxying Correlator to support a circular dependency, but it is not an interface.

 Learn more:
   https://github.com/google/guice/wiki/CAN_NOT_PROXY_CLASS

 1 error

 ======================
 Full classname legend:
 ======================
 Correlator: "jenkins.telemetry.Correlator"
 ========================
 End of classname legend:
 ========================

         at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
         at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:445)
         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
         at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:403)
         at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:394)
         at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:335)
         at hudson.ExtensionList.load(ExtensionList.java:384)
         at hudson.ExtensionList.ensureLoaded(ExtensionList.java:320)
         at hudson.ExtensionList.getComponents(ExtensionList.java:184)
         at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:213)
         at hudson.ExtensionList.ensureLoaded(ExtensionList.java:320)
         at hudson.ExtensionList.iterator(ExtensionList.java:172)
         at hudson.model.User.allocateDefaultPropertyInstancesAsNeeded(User.java:215)
         at hudson.model.User.load(User.java:204)
         at hudson.model.User.<init>(User.java:192)
         at hudson.model.User.getOrCreateById(User.java:543)
         at hudson.model.User.getById(User.java:644)
         at hudson.model.User.get2(User.java:620)
         at hudson.model.User.current(User.java:604)
         at org.datadog.jenkins.plugins.datadog.DatadogUtilities.getUserId(DatadogUtilities.java:739)
         at org.datadog.jenkins.plugins.datadog.listeners.DatadogSaveableListener.onChange(DatadogSaveableListener.java:57)
         at hudson.model.listeners.SaveableListener.fireOnChange(SaveableListener.java:82)
         at hudson.model.Descriptor.save(Descriptor.java:914)
         at jenkins.telemetry.Correlator.<init>(Correlator.java:52)
         at jenkins.telemetry.Correlator$$FastClassByGuice$$14c9d548.GUICE$TRAMPOLINE(<generated>)
         at jenkins.telemetry.Correlator$$FastClassByGuice$$14c9d548.apply(<generated>)
         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
         at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
         at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
         at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
         at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:610)
         at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
         at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
         at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:445)
         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
         at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:403)
         at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:394)
         at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:335)
         at hudson.ExtensionList.load(ExtensionList.java:384)
         at hudson.ExtensionList.ensureLoaded(ExtensionList.java:320)
         at hudson.ExtensionList.iterator(ExtensionList.java:172)
         at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1674)
         at hudson.plugins.git.GitSCM.onLoaded(GitSCM.java:2160)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
         at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
         at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
         at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
         at jenkins.model.Jenkins$5.runTask(Jenkins.java:1170)
         at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
         at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
         at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
         at java.base/java.lang.Thread.run(Unknown Source)
```
